source "https://rubygems.org"
gemspec

gem "jekyll", "~> 4.2"

gem "jekyll-include-cache", group: :jekyll_plugins

gem "html-proofer", "~> 5.0", :group => :development

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
