name: SPFx CI CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Build solution
      run: gulp build

    - name: 'create an empty ./veracode folder'
      run: 'mkdir -p ./veracode'
      
    - name: 'Compress UI Components'
      run: tar -czvf ./veracode/ui-components.tar.gz ./lib

    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: npm-publish-artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ./veracode

